; Listing generated by Microsoft (R) Optimizing Compiler Version 19.32.31328.0 

	TITLE	C:\Users\lib\source\repos\ida03\ida03\ida03.obj
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

CONST	SEGMENT
$SG5650	DB	'This is Func 1,', 00H
$SG5654	DB	'This is Func 1,', 00H
$SG5658	DB	'This is Func 1,', 00H
$SG5661	DB	'Hello World!', 0aH, 00H
CONST	ENDS
PUBLIC	___local_stdio_printf_options
PUBLIC	__vfprintf_l
PUBLIC	_printf
PUBLIC	?fun_3@@YAHH@Z					; fun_3
PUBLIC	?fun_2@@YAHH@Z					; fun_2
PUBLIC	?fun_1@@YAHH@Z					; fun_1
PUBLIC	_main
PUBLIC	?_OptionsStorage@?1??__local_stdio_printf_options@@9@4_KA ; `__local_stdio_printf_options'::`2'::_OptionsStorage
EXTRN	___acrt_iob_func:PROC
EXTRN	___stdio_common_vfprintf:PROC
;	COMDAT ?_OptionsStorage@?1??__local_stdio_printf_options@@9@4_KA
_BSS	SEGMENT
?_OptionsStorage@?1??__local_stdio_printf_options@@9@4_KA DQ 01H DUP (?) ; `__local_stdio_printf_options'::`2'::_OptionsStorage
_BSS	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_main	PROC
; File C:\Users\lib\source\repos\ida03\ida03\ida03.cpp
; Line 30
	push	ebp
	mov	ebp, esp
; Line 31
	push	OFFSET $SG5661
	call	_printf
	add	esp, 4
; Line 32
	push	1
	call	?fun_1@@YAHH@Z				; fun_1
	add	esp, 4
; Line 33
	xor	eax, eax
	pop	ebp
	ret	0
_main	ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_i$ = 8							; size = 4
?fun_1@@YAHH@Z PROC					; fun_1
; File C:\Users\lib\source\repos\ida03\ida03\ida03.cpp
; Line 23
	push	ebp
	mov	ebp, esp
; Line 24
	mov	eax, DWORD PTR _i$[ebp]
	add	eax, OFFSET $SG5658+1
	push	eax
	call	_printf
	add	esp, 4
; Line 25
	mov	ecx, DWORD PTR _i$[ebp]
	push	ecx
	call	?fun_2@@YAHH@Z				; fun_2
	add	esp, 4
; Line 26
	pop	ebp
	ret	0
?fun_1@@YAHH@Z ENDP					; fun_1
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_i$ = 8							; size = 4
?fun_2@@YAHH@Z PROC					; fun_2
; File C:\Users\lib\source\repos\ida03\ida03\ida03.cpp
; Line 17
	push	ebp
	mov	ebp, esp
; Line 18
	mov	eax, DWORD PTR _i$[ebp]
	add	eax, OFFSET $SG5654+2
	push	eax
	call	_printf
	add	esp, 4
; Line 19
	mov	ecx, DWORD PTR _i$[ebp]
	push	ecx
	call	?fun_3@@YAHH@Z				; fun_3
	add	esp, 4
; Line 20
	pop	ebp
	ret	0
?fun_2@@YAHH@Z ENDP					; fun_2
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_i$ = 8							; size = 4
?fun_3@@YAHH@Z PROC					; fun_3
; File C:\Users\lib\source\repos\ida03\ida03\ida03.cpp
; Line 11
	push	ebp
	mov	ebp, esp
; Line 12
	mov	eax, DWORD PTR _i$[ebp]
	add	eax, OFFSET $SG5650+3
	push	eax
	call	_printf
	add	esp, 4
; Line 13
	mov	eax, DWORD PTR _i$[ebp]
; Line 14
	pop	ebp
	ret	0
?fun_3@@YAHH@Z ENDP					; fun_3
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT _printf
_TEXT	SEGMENT
__Result$ = -8						; size = 4
__ArgList$ = -4						; size = 4
__Format$ = 8						; size = 4
_printf	PROC						; COMDAT
; File C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt\stdio.h
; Line 956
	push	ebp
	mov	ebp, esp
	sub	esp, 8
; Line 959
	lea	eax, DWORD PTR __Format$[ebp+4]
	mov	DWORD PTR __ArgList$[ebp], eax
; Line 960
	mov	ecx, DWORD PTR __ArgList$[ebp]
	push	ecx
	push	0
	mov	edx, DWORD PTR __Format$[ebp]
	push	edx
	push	1
	call	___acrt_iob_func
	add	esp, 4
	push	eax
	call	__vfprintf_l
	add	esp, 16					; 00000010H
	mov	DWORD PTR __Result$[ebp], eax
; Line 961
	mov	DWORD PTR __ArgList$[ebp], 0
; Line 962
	mov	eax, DWORD PTR __Result$[ebp]
; Line 963
	mov	esp, ebp
	pop	ebp
	ret	0
_printf	ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT __vfprintf_l
_TEXT	SEGMENT
__Stream$ = 8						; size = 4
__Format$ = 12						; size = 4
__Locale$ = 16						; size = 4
__ArgList$ = 20						; size = 4
__vfprintf_l PROC					; COMDAT
; File C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt\stdio.h
; Line 644
	push	ebp
	mov	ebp, esp
; Line 645
	mov	eax, DWORD PTR __ArgList$[ebp]
	push	eax
	mov	ecx, DWORD PTR __Locale$[ebp]
	push	ecx
	mov	edx, DWORD PTR __Format$[ebp]
	push	edx
	mov	eax, DWORD PTR __Stream$[ebp]
	push	eax
	call	___local_stdio_printf_options
	mov	ecx, DWORD PTR [eax+4]
	push	ecx
	mov	edx, DWORD PTR [eax]
	push	edx
	call	___stdio_common_vfprintf
	add	esp, 24					; 00000018H
; Line 646
	pop	ebp
	ret	0
__vfprintf_l ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ___local_stdio_printf_options
_TEXT	SEGMENT
___local_stdio_printf_options PROC			; COMDAT
; File C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt\corecrt_stdio_config.h
; Line 90
	push	ebp
	mov	ebp, esp
; Line 92
	mov	eax, OFFSET ?_OptionsStorage@?1??__local_stdio_printf_options@@9@4_KA ; `__local_stdio_printf_options'::`2'::_OptionsStorage
; Line 93
	pop	ebp
	ret	0
___local_stdio_printf_options ENDP
_TEXT	ENDS
END
