; Listing generated by Microsoft (R) Optimizing Compiler Version 19.32.31328.0 

	TITLE	C:\Users\lib\source\repos\ida03\ida03\ida03.obj
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

CONST	SEGMENT
$SG5650	DB	'This is Func 1 %d', 0aH, 00H
	ORG $+1
$SG5654	DB	'This is Func 1 %d', 0aH, 00H
	ORG $+1
$SG5658	DB	'This is Func 1 %d', 0aH, 00H
	ORG $+1
$SG5661	DB	'Hello World!', 0aH, 00H
CONST	ENDS
PUBLIC	___local_stdio_printf_options
PUBLIC	__vfprintf_l
PUBLIC	_printf
PUBLIC	?fun_3@@YAHH@Z					; fun_3
PUBLIC	?fun_2@@YAHH@Z					; fun_2
PUBLIC	?fun_1@@YAHH@Z					; fun_1
PUBLIC	_main
PUBLIC	?_OptionsStorage@?1??__local_stdio_printf_options@@9@4_KA ; `__local_stdio_printf_options'::`2'::_OptionsStorage
EXTRN	___acrt_iob_func:PROC
EXTRN	___stdio_common_vfprintf:PROC
;	COMDAT ?_OptionsStorage@?1??__local_stdio_printf_options@@9@4_KA
_BSS	SEGMENT
?_OptionsStorage@?1??__local_stdio_printf_options@@9@4_KA DQ 01H DUP (?) ; `__local_stdio_printf_options'::`2'::_OptionsStorage
_BSS	ENDS
; Function compile flags: /Ogtpy
_TEXT	SEGMENT
_main	PROC
; File C:\Users\lib\source\repos\ida03\ida03\ida03.cpp
; Line 31
	push	OFFSET $SG5661
	call	_printf
; Line 24
	push	2
	push	OFFSET $SG5658
	call	_printf
; Line 18
	push	3
	push	OFFSET $SG5654
	call	_printf
; Line 12
	push	4
	push	OFFSET $SG5650
	call	_printf
	add	esp, 28					; 0000001cH
; Line 33
	xor	eax, eax
	ret	0
_main	ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
_TEXT	SEGMENT
_i$ = 8							; size = 4
?fun_1@@YAHH@Z PROC					; fun_1
; File C:\Users\lib\source\repos\ida03\ida03\ida03.cpp
; Line 23
	push	esi
; Line 24
	mov	esi, DWORD PTR _i$[esp]
	lea	eax, DWORD PTR [esi+1]
	push	eax
	push	OFFSET $SG5658
	call	_printf
; Line 18
	lea	ecx, DWORD PTR [esi+2]
	push	ecx
	push	OFFSET $SG5654
	call	_printf
; Line 12
	lea	ecx, DWORD PTR [esi+3]
	push	ecx
	push	OFFSET $SG5650
	call	_printf
	add	esp, 24					; 00000018H
; Line 25
	mov	eax, esi
	pop	esi
; Line 26
	ret	0
?fun_1@@YAHH@Z ENDP					; fun_1
_TEXT	ENDS
; Function compile flags: /Ogtpy
_TEXT	SEGMENT
_i$ = 8							; size = 4
?fun_2@@YAHH@Z PROC					; fun_2
; File C:\Users\lib\source\repos\ida03\ida03\ida03.cpp
; Line 17
	push	esi
; Line 18
	mov	esi, DWORD PTR _i$[esp]
	lea	ecx, DWORD PTR [esi+2]
	push	ecx
	push	OFFSET $SG5654
	call	_printf
; Line 12
	lea	ecx, DWORD PTR [esi+3]
	push	ecx
	push	OFFSET $SG5650
	call	_printf
	add	esp, 16					; 00000010H
; Line 19
	mov	eax, esi
	pop	esi
; Line 20
	ret	0
?fun_2@@YAHH@Z ENDP					; fun_2
_TEXT	ENDS
; Function compile flags: /Ogtpy
_TEXT	SEGMENT
_i$ = 8							; size = 4
?fun_3@@YAHH@Z PROC					; fun_3
; File C:\Users\lib\source\repos\ida03\ida03\ida03.cpp
; Line 11
	push	esi
; Line 12
	mov	esi, DWORD PTR _i$[esp]
	lea	ecx, DWORD PTR [esi+3]
	push	ecx
	push	OFFSET $SG5650
	call	_printf
	add	esp, 8
; Line 13
	mov	eax, esi
	pop	esi
; Line 14
	ret	0
?fun_3@@YAHH@Z ENDP					; fun_3
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT _printf
_TEXT	SEGMENT
__Format$ = 8						; size = 4
_printf	PROC						; COMDAT
; File C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt\stdio.h
; Line 956
	push	esi
; Line 960
	mov	esi, DWORD PTR __Format$[esp]
	push	1
	call	___acrt_iob_func
	add	esp, 4
; Line 645
	lea	ecx, DWORD PTR __Format$[esp+4]
	push	ecx
	push	0
	push	esi
	push	eax
	call	___local_stdio_printf_options
	push	DWORD PTR [eax+4]
	push	DWORD PTR [eax]
	call	___stdio_common_vfprintf
	add	esp, 24					; 00000018H
; Line 962
	pop	esi
; Line 963
	ret	0
_printf	ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT __vfprintf_l
_TEXT	SEGMENT
__Stream$ = 8						; size = 4
__Format$ = 12						; size = 4
__Locale$ = 16						; size = 4
__ArgList$ = 20						; size = 4
__vfprintf_l PROC					; COMDAT
; File C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt\stdio.h
; Line 645
	push	DWORD PTR __ArgList$[esp-4]
	push	DWORD PTR __Locale$[esp]
	push	DWORD PTR __Format$[esp+4]
	push	DWORD PTR __Stream$[esp+8]
	call	___local_stdio_printf_options
	push	DWORD PTR [eax+4]
	push	DWORD PTR [eax]
	call	___stdio_common_vfprintf
	add	esp, 24					; 00000018H
; Line 646
	ret	0
__vfprintf_l ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ___local_stdio_printf_options
_TEXT	SEGMENT
___local_stdio_printf_options PROC			; COMDAT
; File C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt\corecrt_stdio_config.h
; Line 92
	mov	eax, OFFSET ?_OptionsStorage@?1??__local_stdio_printf_options@@9@4_KA ; `__local_stdio_printf_options'::`2'::_OptionsStorage
; Line 93
	ret	0
___local_stdio_printf_options ENDP
_TEXT	ENDS
END
